### ISSUE TITLE
Feature Request: Multi-Channel Support with Per Channel Twitter-IDs Support

### ISSUE THREAD

**Issue by JustAKat** [dracarys18/TweetBot#13]
Hi,

Was wondering if it might be possible for you to consider adding multi-channel support with your planned future rewrite?

Possible example of the configuration to outline the suggestion better:

```YAML
Twitter:
  ACCESS_TOKEN: "ACCESS_TOKEN_HERE"
  ACCESS_TOKEN_SECRET: "ACCESS_TOKEN_SECRET_HERE"
  CONSUMER_KEY: "API_KEY_HERE"
  CONSUMER_SECRET: "API_KEY_SECRET_HERE"
Telegram:
 - IncludeRetweet: false
   IncludeUserReply: false
   IncludeReplyToUser: false
   custom_message: ""
   twitter_ids: ['utdreport', 'ManUnitedZone_']
   chat_id:
     - "-1002233445566"
     - "-1004455667788"
 - IncludeRetweet: true
   IncludeUserReply: true
   IncludeReplyToUser: false
   custom_message: ""
   twitter_ids: ['manutd']
   chat_id:
     - "-1004455667788"
```
